# Generated by Django 3.2.5 on 2021-07-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='places'),
        ),
    ]
