# Generated by Django 3.2.5 on 2021-07-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.AddField(
            model_name='place',
            name='cities',
            field=models.ManyToManyField(to='places.City'),
        ),
    ]
